site_name: GenAI Bench
site_description: Unified, accurate, and beautiful LLM Benchmarking
site_author: GenAI Bench Team
site_url: https://github.com/sgl-project/genai-bench

# Repository
repo_name: sgl-project/genai-bench
repo_url: https://github.com/sgl-project/genai-bench
edit_uri: edit/main/docs/

# Theme
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
    - json
  navigation_depth: 4
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  style_external_links: true

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Command Line Interface: user-guide/cli.md
    - Tasks and Benchmarks: user-guide/tasks.md
    - Results Analysis: user-guide/analysis.md
  - Examples:
    - Basic Benchmarks: examples/basic-benchmarks.md
  - API Reference:
    - Overview: api/overview.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      anchorlink: true
      permalink: true
      title: On this page
  - tables
  - fenced_code

# Extra
extra:
  version: 1.0.0

# Copyright
copyright: Copyright &copy; 2024 GenAI Bench Team 